### PR TITLE
Change question that threw me off when taking it.

### PR DESCRIPTION
**Pull request by DefunctLizard**
There are a lot of people who think that drug use is not a victimless crime, but **DO** think that victimless crimes should not be crimes at all.

Is this not reasonable?

### CODE REVIEW

**Comment by Genora51** [comment]
This has been raised in another issue; I think it's useful to have an example though (even if that example isn't drug use).

Are there any clear [and ideally divisive] examples of victimless crimes which aren't already questions in the test?

**Comment by DefunctLizard** [comment]
Don't quote me on this but I think this is the only question with an example. Most people know what a victimless crime is (it is self explanatory).

**Comment by Genora51** [comment]
I'm inclined to agree with you there, and the question would definitely work without an example.

My only worry then is whether the question is sufficiently divisive - ideally each question on the test should have a fairly even split between agree / disagree to prevent overall bias, and I'm concerned that if there isn't an example given which is a divisive and debated issue that it will be biased towards agree in this case.

**Comment by Genora51** [comment]
I've given this pull request some thought, and I think this question should be changed for a different issue with similar political division - assisted suicide. This eliminates the ambiguity and semantic quibbles of the nature of a 'victimless crime' by changing the question to something like:

    Physician-assisted suicide should be legal.
Let me know if this is a good alternative [it also solves the issue of this question being a duplicate of Q55].

**Comment by brmbrmcar** [comment]
I think that the question perhaps should be focused more on drug use than it being victimless, as people's perceptions of what should be a crime is more useful than asking them if they think victimless crimes should be crimes in my opinion. I would myself perhaps be convinced that drug use could cause harm to others (though in itself I still think it is victimless), but I would still support its decriminalisation. Whereas it would take a rather extreme view point to support criminalising what are perceived to the taker as victimless acts.

**Comment by Genora51** [comment]
This is absolutely correct, and the ambiguity in the word "victimless" is my biggest issue in this question. However, question 55 ("Drug use should be legalized or decriminalized") deals with this exact issue in a better, more specific way. So I think the topic of this "victimless crimes" question should be shifted onto a different, also specific issue other than drugs, in this case perhaps assisted suicide as I suggested earlier.

**Comment by brmbrmcar** [comment]
That would make sense, I forgot that the other question on drug use existed.

**Comment by ConnorWilloughby2** [comment]
To move it into a victimless crime i believe that a good example of 'victimless' would be content piracy. 

Most people are aware of the large incomes from feature films / albums and would consider this to be victimless.

**Comment by DefunctLizard** [comment]
ConnorWilloughby2:





I think many people would disagree that piracy is not victimless. Not that I haven't contributed : )

**Comment by DefunctLizard** [comment]
Physician Assisted Suicide is now the pull request, I do think people would consider it a victimless crime.

**Comment by Genora51** [comment]
Closing this PR since this change has already been separately committed to master.

**Pull request closed without merging**
